default: &default 
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: desarrollo_db_cv

test:
  <<: *default
  database: prueba_db_cv

production:
  <<: *default
  database: produccion_db_cv
